name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:  eu-central-1 

    - name: Build project
      run: npm run build

    - name: Deploy to AWS
      run: |
        # Add your deployment steps here, such as using AWS CLI to deploy to S3, Elastic Beanstalk, etc.
        # Example:
        # aws s3 sync dist/ s3://your-bucket-name

    - name: Run tests
      run: npm test



